### PR TITLE
Expose assessments from pattern analyzer

### PR DESCRIPTION
**Pull request by jeffakolb**
new BaseBlob method `sentiment_assessments`
new optional flag to PatternAnalyzer.analyze

### CODE REVIEW

**Comment by sloria** [comment]
Thanks for the PR @jeffakolb . I am open to merging this. Just a couple things.

- Add tests
- Add yourself to AUTHORS.rst

Once those are addressed, this should be good to merge.

**Comment by jeffakolb** [comment]
@sloria Added tests and contributor entry, as requested.

**Comment by sloria** [comment]
@jeffakolb Thanks! Would you mind getting this up to date with the `dev` branch pls?

**Comment by jeffakolb** [comment]
@sloria done

**Comment by sloria** [comment]
By the way, I'm starting to use something along the lines of the [Pull Request Hack](http://felixge.de/2013/03/11/the-pull-request-hack.html). Basically, if you get a PR merged in, you get an invite to have commit access.

No pressure to do any more work than you already have. Just want to open the door to further collaboration. =)

**Pull request merged**
