### PR TITLE
Fix Error 503 Service Unavailable

### PR DESCRIPTION
**Pull request by EpicJhon**

### CODE REVIEW

**Comment by sloria** [comment]
Ref #137 .

**Comment by sloria** [comment]
@EpicJhon Thanks for the PR! Would you mind getting the tests passing?

**Comment by sloria** [comment]
https://github.com/sloria/TextBlob/pull/139 also attempts to solve the 503 issue. @EpicJhon can you confirm that this reliably fixes the issue?

**Comment by EpicJhon** [comment]
@sloria The solution is reliable, implemented in my own plugin and I have not had any 503 error so far:
https://github.com/EpicJhon/Hexchat-Google-Translator-Plugin

Fail tests:

"ERROR: test_tk_parameter_included_in_requests (tests.test_translate.TestTranslator)" > I'll look at whether a solution without including the data in the URL is viable

FAIL: test_translate_non_ascii (tests.test_translate.TestTranslatorIntegration)
FAIL: test_translate_text (tests.test_translate.TestTranslatorIntegration)

**Comment by sloria** [comment]
@EpicJhon Are you still working on this? Would love to get this merged and release the fix.

**Comment by sloria** [comment]
Actually, I'll go ahead and wrap up this PR, i.e. get the tests passing. Thanks again for the contribution.

**Pull request merged**
